apiVersion: "v1"
kind: "Endpoints"
metadata:
  name: "rabbitmq-endpoint"
subsets:
  -
    addresses:
      -
        ip: "10.128.0.27"
    ports:
      -
        port: 5672
        name: "rabbitmq-server"
      - 
        port: 15672
        name: "rabbitmq-mgm"