version: '3'

services:
  postgres:
    image: postgres:14
    container_name: container-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      ports: 
        - "5432:5432"
      restart: always
  rabbitmq:
    image: rabbitmq:3-management
    container_name: container-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always